### ISSUE TITLE
Running payout server, nodejs crashes soon after payout.

### ISSUE THREAD

**Issue by samuelbetio** [ROBLOXStudio/roblox-js#1]

**Comment by samuelbetio** [comment]
[Primary] login complete.
[Primary] Token Connected.
[Primary] Sent A Payout.
events.js:141
throw er; // Unhandled 'error' event
^

Error: read ECONNRESET
at exports._errnoException (util.js:870:11)
at TLSWrap.onread (net.js:544:26)
